
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'zh-cn'
    cache: true
    cache_dir: /config/tts
    time_memory: 57600
    base_url: http://192.168.1.7:8123

media_player:
  - platform: lg_netcast
    access_token: '214850'
    host: 10.0.0.227

yeelight:
  devices:
    192.168.1.225:
      name: Bedroom

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/802
    extra_arguments: -q:v 2 -s 900x600
    name: garden
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/202
    extra_arguments: -q:v 2 -s 900x600
    name: front
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/102
    extra_arguments: -q:v 2 -s 900x600
    name: roof

## booleans to be used
input_boolean: !include input_boolean.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
