
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# config lovelace UI from yaml file
lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate
    language: 'zh-cn'
    cache: true
    cache_dir: /config/tts
    time_memory: 57600
    base_url: http://192.168.1.7:8123

media_player:
  - platform: lg_netcast
    access_token: '214850'
    host: 10.0.0.227

yeelight:
  devices:
    192.168.1.225:
      name: Bedroom

mqtt:
  alarm_control_panel:
    - state_topic: "homeassistant/alarm_control_panel/area1/state"
      name: alert
      code: "1573"
      payload_arm_home: "ARM_HOME"
      payload_disarm: "DISARM"
      command_topic: "homeassistant/alarm_control_panel/area1/command"
# sonoff lights
  light: !include sonoff/sonoff-lights.yaml
# sonoff sensors
  sensor: !include sonoff/sonoff-sensors.yaml
# sonoff + SR501 PIR
  binary_sensor: !include sonoff/sonoff-pir.yaml

homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - sensor
      - input_boolean
      - media_player
  ip_address: '192.168.1.7'

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/802
    extra_arguments: -q:v 2 -s 900x600
    name: garden
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/202
    extra_arguments: -q:v 2 -s 900x600
    name: front
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/102
    extra_arguments: -q:v 2 -s 900x600
    name: roof
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://admin:82111e&109A@192.168.1.206:554/Streaming/Channels/302
    extra_arguments: -q:v 2 -s 900x600
    name: entrance


# actionable notification needs this
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'ARM_ALARM'
            title: 'Arm'
            activationMode: 'foreground'
            authenticationRequired: true
            destructive: true
          - identifier: 'DISARM_ALARM'
            title: 'Disarm'
            activationMode: 'background'
            destructive: false

# the group notify is different from group syntex
notify:
  name: ALL_DEVICES
  platform: group
  services:
    - service: mobile_app_ceci
    - service: mobile_app_terry

## booleans to be used
input_boolean: !include input_boolean.yaml
## automation folder
automation: !include_dir_merge_list automation
## timer
timer: !include timers.yaml

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# customize entity IDs
homeassistant:
  customize: !include customize.yaml

#frontend: !include frontend.yaml
panel_custom: !include panel_custom.yaml
