title: Home
views:
# first page
  - cards:
      - type: button
        name: Alert Mode
        icon: "mdi:shield-home-outline"
        entity: alarm_control_panel.area1
        show_state: true
        tap_action:
          action: call-service
          confirmation:
            text: "Sure to set alarm?"
          service: script.into_alert
      - type: entity-filter
        show_empty: false
        entities:
          - light.loft
          - binary_sensor.door_window_sensor_158d000121ba10
          - binary_sensor.door_window_sensor_158d000224b01c
          - binary_sensor.door_window_sensor_158d000228601e
#          - binary_sensor.door_window_sensor_158d00022bf88d
          - binary_sensor.door_window_sensor_158d00022c3a10
          - binary_sensor.0x00158d0003542f22_lock
          - binary_sensor.0x00158d0003542f22_lock_reverse
          - binary_sensor.alarm_bath_window
          - binary_sensor.alarm_bedroom_window
          - binary_sensor.alarm_kitchen_pir
          - binary_sensor.alarm_kitchen_shock
          - binary_sensor.alarm_living_hall_pir
          - binary_sensor.alarm_loft_pir
          - binary_sensor.alarm_stair_pir
          - binary_sensor.alarm_study_pir
          - binary_sensor.alarm_toilet_pir
        state_filter:
          - 'on'
        card:
          title: 注意
          show_header_toggle: false
      - type:  weather-forecast
        entity: weather.home
        secondary_info_attribute: humidity
      - type: iframe
        url: https://embed.windy.com/
        aspect_ratio: 50%
      - type: gauge
        min: 0
        max: 60
        severity:
          green: 50
          yellow: 35
          red: 0
        theme: default
        entity: sensor.speedtest_download
        name: 网速
    badges:
      - device_tracker.terrys_iphone_2
      - device_tracker.unifi_08_fa_79_38_90_df_default
      - sensor.temp_xiaoxi
      - sensor.humidity_xiaoxi
      - sensor.temp_xiaoxin
      - sensor.humidity_xiaoxin
    path: default_view
    title: Home
# lights page
  - cards:
      - type: entities
        entities:
          - light.kitchen
          - light.bath
          - light.playroom
          - light.landing
          - light.hall
          - light.dining
          - light.living_room
          - light.toilet
          - light.loft
          - light.gateway_light_34ce00838c96
          - light.bedroom
        title: 灯光
      - type: entities
        entities:
          - input_boolean.pir_hall
          - input_boolean.pir_living_room
          - input_boolean.pir_kitchen
          - input_boolean.pir_dining
          - input_boolean.pir_toilet
          - input_boolean.pir_bath
          - input_boolean.pir_landing
#          - input_boolean.night_mode
        title: 移动监测
    badges: []
    title: Lights
# alarm page
  - cards:
      - type: alarm-panel
        entity: alarm_control_panel.alert
        name: 警报
        states:
          - arm_home
      - type: entities
        entities:
          - binary_sensor.alarm_bath_window
          - binary_sensor.alarm_bedroom_window
          - binary_sensor.alarm_kitchen_pir
          - binary_sensor.alarm_kitchen_shock
          - binary_sensor.alarm_living_hall_pir
          - binary_sensor.alarm_loft_pir
          - binary_sensor.alarm_stair_pir
          - binary_sensor.alarm_study_pir
          - binary_sensor.alarm_toilet_pir
    badges: []
    title: Alarm
# CCTV page
  - cards:
      - type: picture-entity
        entity: camera.front
        camera_view: live
      - type: picture-entity
        entity: camera.garden
        camera_view: live
      - type: picture-entity
        entity: camera.roof
        camera_view: live
      - type: picture-entity
        entity: camera.entrance
        camera_view: live
    badges: []
    title: CCTV
# media page
  - cards:
      - type: media-control
        entity: media_player.lg_tv_remote
      - type: media-control
        entity: media_player.living_room_speaker
      - type: media-control
        entity: media_player.kitchen_tv
      - type: media-control
        entity: media_player.kitchen_mini
    badges: []
    title: MEDIA

