###############################################################
#
#
# Prepare for Greetings
#
#
##############################################################
#- alias: Prepare Greetings
#  hide_entity: true
#  initial_state: 'on'
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.door_window_sensor_158d000224b01c
#      to: 'off'
#  action:
#    - service: automation.turn_on
#      entity_id: automation.welcome_greetings
#    - delay: '00:00:15'
#    - service: automation.turn_off
#      entity_id: automation.welcome_greetings
#
##################################################################
##
##
## Welcome Greetings
##
##
#################################################################
#
## Play welcome audio on xiaomi
#- alias: Welcome Greetings
#  hide_entity: true
#  initial_state: 'off'
#  trigger:
#    - platform: state
#      entity_id:
#        - binary_sensor.hall
#      to: 'on'
#  action:
#  - service: xiaomi_aqara.play_ringtone
#    data:
#      gw_mac: '34:ce:00:83:8c:96'
#      ringtone_id: '10002'
#      ringtone_vol: '30'
#  - service: light.turn_on
#    entity_id: light.gateway_light_34ce00838c96
#    data_template:
#      rgb_color: ['{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}']
#      brightness: 50
#  - delay:
#      seconds: 0.5
#  - service: light.turn_on
#    entity_id: light.gateway_light_34ce00838c96
#    data_template:
#      rgb_color: ['{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}']
#      brightness: 50
#  - delay:
#      seconds: 0.5
#  - service: light.turn_on
#    entity_id: light.gateway_light_34ce00838c96
#    data_template:
#      rgb_color: ['{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}']
#      brightness: 50
#  - delay:
#      seconds: 0.5
#  - service: light.turn_on
#    entity_id: light.gateway_light_34ce00838c96
#    data_template:
#      rgb_color: ['{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}']
#      brightness: 50
#  - delay:
#      seconds: 0.5
#  - service: light.turn_on
#    entity_id: light.gateway_light_34ce00838c96
#    data_template:
#      rgb_color: ['{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}', '{{ (range(0, 255)|random|int) }}']
#      brightness: 50
#  - delay:
#      seconds: 0.5
#  - service: light.turn_off
#    entity_id: light.gateway_light_34ce00838c96
#  - service: automation.turn_off
#    entity_id: automation.welcome_greetings

################################################################
#
#
# Start Homekit after yeelight appears
#
#
################################################################

- alias: Start Homekit
  trigger:
    - platform: homeassistant
      event: start
  action:
    - wait_template: >-
        {% if not states.light.bedroom %}
          false
        {% else %}
          true
        {% endif %}
      timeout: 00:10 #max timeout for 10 minutes
      continue_on_timeout: true
    - service: homekit.start

################################################################
#
#
# Doorbell notification on google home and kitchen lights
#
#
################################################################

- alias: Doorbell Notification
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000183e596
# if we want all button press to trigger action, then no
# condition is needed
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.click_type in ['single', 'double'] }}
  action:
  - service: tts.google_translate_say
    entity_id: media_player.family_room_speaker
    data:
      message: '有客人到'
  - service: light.turn_on
    entity_id: light.kitchen
  - service: light.turn_off
    entity_id: light.dining
  - delay:
      seconds: 0.5
  - service: light.turn_on
    entity_id: light.dining
  - service: light.turn_off
    entity_id: light.kitchen
  - delay:
      seconds: 0.5
  - service: light.turn_on
    entity_id: light.kitchen
  - service: light.turn_off
    entity_id: light.dining
  - delay:
      seconds: 0.5
  - service: light.turn_on
    entity_id: light.dining
  - service: light.turn_off
    entity_id: light.kitchen
  - delay:
      seconds: 0.5
  - service: light.turn_off
    entity_id: light.dining

################################################################
#
#
# Xiaomi Wireless Button
# Toggle Bath Light on double press
# Toggle Bedroom light on single press
#
#
################################################################
- alias: Toggle bath light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f37855
      click_type: double
  action:
    service: light.toggle
    entity_id: light.bath

- alias: Toggle bedroom light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f37855
      click_type: single
  action:
    service: light.toggle
    entity_id: light.bedroom

################################################################
#
#
# Alarm notification
# Send out notification to HA app when Alarm state changes
#
#
################################################################
- alias: Alarm notification
  trigger:
    platform: state
    entity_id: alarm_control_panel.area1
  action:
    service: notify.mobile_app_terrys_iphone
    data:
      message: >
        The alarm has been set to {{ states("alarm_control_panel.area1") }}

################################################################
#
#
# Auto arm/disarm Alarm
# Set Alarm when there is nobody at home
# There will be a roughly 4 mins delay of device tracker to
# notice people is not in, but people get connected will be
# noticed immdiately
#
#
################################################################
- alias: Auto arm
  trigger:
    platform: state
    entity_id: group.people_at_home
    to: "not_home"
  condition:
    condition: state
    entity_id: alarm_control_panel.area1
    state: "disarmed"
  action:
    - service: script.into_alert
    - service: notify.mobile_app_terrys_iphone
      data:
        title: "Alarm Warning!"
        message: "Nobody is at home and the alarm is not set. Homeassistant will automatically arm it unless you cancel it manually."
        data:
          push:
            category: "alarm"
            sound:
              name: default
              critical: 1
              volume: 1.0

- alias: Auto disarm
  trigger:
    platform: state
    entity_id: group.people_at_home
    to: "home"
  condition:
    condition: state
    entity_id: alarm_control_panel.area1
    state:
      - "armed_away"
      - "armed_home"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.area1
